### ISSUE TITLE
Customizable font size/color

### ISSUE THREAD

**Issue by dyarfaradj** [yishn/spotify-lyrics#1]
I love the app, nice work man!
I have some suggestions though.
Can you add options where users can choose fontsize, fontcolor?
I mean allowing users to customize the app would be dope!

**Comment by yishn** [comment]
First of all, thank you! This project is a very simple and minimal app. I don't think that adding the option to customize font size/color is appropriate. That said, you can always fork this repository and add your custom rules in the [CSS file](https://github.com/yishn/spotify-lyrics/blob/master/browser/style.css#L18).
