### ISSUE TITLE
Does not detect currently playing song

### ISSUE THREAD

**Issue by AndreasBackx** [yishn/spotify-lyrics#4]
The application doesn't seem to be able to detect the currently playing song on Spotify. I'm running Arch Linux 4.15.10-1, npm 5.7.1, and node 9.9.0. Would love to get this to work. I'd love to give more information if you tell me what you need and how I can get it.

**Comment by yishn** [comment]
Hmm... Unfortunately, I can't test this on Linux at all. spotify-lyrics depends on [node-spotify-webhelper](https://github.com/nadavbar/node-spotify-webhelper) for communicating with Spotify. Make sure the SpotifyWebHelper process is running.

Some time ago, I received a PR from @sudhackar which fixed some stuff and if I remember correctly, they were using Linux. @sudhackar, maybe you can help?

**Comment by AndreasBackx** [comment]
I looked at that issue and checked whether it was using the port mentioned, and it was. But now that I look at the other diff line, it changes from HTTPS to HTTP. But I doubt that that wasn't changed as well. I'd love to help fix the issue.

**Comment by yishn** [comment]
Closing since out of date.
